export const industries = [
  { slug: 'education', icon: 'graduation', name: 'Education', blurb: 'Colleges, coaching centres and training institutes.', items: ['Institution website', 'Online enquiry and admissions forms', 'Course catalogue and batch management', 'Student and fee tracking', 'Results and certificate generation'] },
  { slug: 'schools', icon: 'building', name: 'Schools', blurb: 'Everything a school needs to run and communicate.', items: ['School website', 'Fee management', 'Attendance', 'Parent portal', 'Teacher portal', 'Timetables', 'Examination management'] },
  { slug: 'healthcare', icon: 'heart', name: 'Healthcare', blurb: 'Hospitals, diagnostic centres and care providers.', items: ['Service and department website', 'Appointment and report-request flows', 'Patient communication and reminders', 'Staff scheduling tools', 'Secure internal dashboards'] },
  { slug: 'clinics', icon: 'heart', name: 'Clinics', blurb: 'Help patients find you, book and show up.', items: ['Clinic website', 'Appointment booking', 'Patient enquiries', 'Reminder systems', 'Doctor schedule management'] },
  { slug: 'real-estate', icon: 'home', name: 'Real Estate', blurb: 'Turn property enquiries into site visits and sales.', items: ['Property catalogue', 'Lead collection', 'Site-visit booking', 'CRM', 'Automated follow-up'] },
  { slug: 'interior-design', icon: 'palette', name: 'Interior Design', blurb: 'Show your work and manage client projects.', items: ['Portfolio website', 'Project gallery', 'Enquiry and consultation booking', 'Client project tracker', 'Quotation generation'] },
  { slug: 'retail', icon: 'store', name: 'Retail', blurb: 'Stores that want to sell and serve better.', items: ['Store website', 'Online catalogue and ordering', 'Inventory tracking', 'Customer loyalty and offers', 'Sales dashboards'] },
  { slug: 'professional-services', icon: 'briefcase', name: 'Professional Services', blurb: 'Consultants, accountants, lawyers and agencies.', items: ['Credibility-first website', 'Consultation booking', 'Client portal', 'Document sharing', 'Lead capture and follow-up'] },
  { slug: 'startups', icon: 'rocket', name: 'Startups', blurb: 'Take an idea to a working first release.', items: ['Product website and landing pages', 'Minimum viable product build', 'Admin dashboard', 'Mobile app', 'Technical guidance and scaling'] },
  { slug: 'restaurants', icon: 'utensils', name: 'Restaurants', blurb: 'Fill tables and simplify orders.', items: ['Restaurant website with menu', 'Table reservations', 'Online ordering', 'Event and catering enquiries', 'Local search presence'] },
  { slug: 'hospitality', icon: 'bed', name: 'Hospitality', blurb: 'Hotels, guest houses and venues.', items: ['Property website', 'Room enquiry and booking', 'Guest communication automation', 'Booking dashboards', 'Review and feedback collection'] },
  { slug: 'manufacturing', icon: 'factory', name: 'Manufacturing', blurb: 'Digitise operations and win more buyers.', items: ['Company and product website', 'Quotation and enquiry management', 'Inventory and production tracking', 'Dealer and distributor portal', 'Reports and dashboards'] },
  { slug: 'e-commerce', icon: 'cart', name: 'E-commerce', blurb: 'Online stores built to convert.', items: ['Online store', 'Payment gateway integration', 'Order management', 'Inventory sync', 'Customer notifications'] },
  { slug: 'events', icon: 'calendar', name: 'Events', blurb: 'From small gatherings to large programmes.', items: ['Event website', 'Registration and ticketing', 'Attendee management', 'Schedule and speaker pages', 'Reminders and updates'] },
  { slug: 'local-businesses', icon: 'pin', name: 'Local Businesses', blurb: 'Shops, services and everyday businesses.', items: ['Professional website', 'Local search setup', 'Click-to-call and WhatsApp enquiries', 'Simple booking', 'Ongoing maintenance'] }
];
